ALTER TABLE pantry ADD COLUMN amount REAL DEFAULT NULL;
ALTER TABLE pantry ADD COLUMN unit TEXT DEFAULT NULL;
ALTER TABLE shopping_list ADD COLUMN amount REAL DEFAULT NULL;
ALTER TABLE shopping_list ADD COLUMN unit TEXT DEFAULT NULL;
