ALTER TABLE pantry ADD COLUMN density REAL DEFAULT NULL;
ALTER TABLE pantry ADD COLUMN density_unit TEXT DEFAULT NULL;
ALTER TABLE shopping_list ADD COLUMN density REAL DEFAULT NULL;
ALTER TABLE shopping_list ADD COLUMN density_unit TEXT DEFAULT NULL;
